config/routes.rb
Bazaarworldofgaming::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'welcome#index'
  
  match '/signup', to: 'users#new', via: 'get'
  get "game/search"
  post "game/add"
  resources :game 

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bazaarworldofgaming</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery.dotdotdot" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Bazaar World", root_path, id: "logo" %>
          <nav>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Games",    '#' %></li>
              <% if signed_in? %>
                <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
            </ul>
          </nav>
        </div>
      </div>
</header>
<div class = "flash_container">
<% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
</div>
<%= yield %>


</body>
</html>